name: Unzip
on: workflow_dispatch
permissions:
  contents: write
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          unzip -q rayeh-jay.zip -d tmp
          rm rayeh-jay.zip
          rm -rf tmp/rayeh-jay/.github
          cp -r tmp/rayeh-jay/. .
          rm -rf tmp
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Extract project"
          git push
